config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :scrapings
  resources :form_fields
  resources :prices
  resources :exchange_offices
  resources :messages
  resources :type_form_fields
  resources :price_types
  resources :money

  root 'main#index'

  get '/best_prices', to: 'main#best_prices'
  get '/:exchange_office', to: 'main#price_today_exchange_office'
  get '/date/:exchange_office/:date', to: 'main#price_date_exchange_office'
  get '/all/:exchange_office', to: 'main#all_price_exchange_office'

  post '/main/scraping_done'
  post '/main/scraping_not_done'
  post '/main/destroy_scraping'
  post '/main/replicate_price'

end

app/models/exchange_office.rb
class ExchangeOffice < ActiveRecord::Base
  belongs_to :message
end

app/controllers/exchange_offices_controller.rb
class ExchangeOfficesController < ApplicationController
  before_action :set_exchange_office, only: [:show, :edit, :update, :destroy]

  # GET /exchange_offices
  # GET /exchange_offices.json
  def index
    @exchange_offices = ExchangeOffice.all
  end

  # GET /exchange_offices/1
  # GET /exchange_offices/1.json
  def show
  end

  # GET /exchange_offices/new
  def new
    @exchange_office = ExchangeOffice.new
  end

  # GET /exchange_offices/1/edit
  def edit
  end

  # POST /exchange_offices
  # POST /exchange_offices.json
  def create
    @exchange_office = ExchangeOffice.new(exchange_office_params)

    respond_to do |format|
      if @exchange_office.save
        format.html { redirect_to @exchange_office, notice: 'Exchange office was successfully created.' }
        format.json { render :show, status: :created, location: @exchange_office }
      else
        format.html { render :new }
        format.json { render json: @exchange_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchange_offices/1
  # PATCH/PUT /exchange_offices/1.json
  def update
    respond_to do |format|
      if @exchange_office.update(exchange_office_params)
        format.html { redirect_to @exchange_office, notice: 'Exchange office was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange_office }
      else
        format.html { render :edit }
        format.json { render json: @exchange_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchange_offices/1
  # DELETE /exchange_offices/1.json
  def destroy
    @exchange_office.destroy
    respond_to do |format|
      format.html { redirect_to exchange_offices_url, notice: 'Exchange office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange_office
      @exchange_office = ExchangeOffice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_office_params
      params.require(:exchange_office).permit(:name, :url_page, :message_id, :scraping_done)
    end
end

app/helpers/exchange_offices_helper.rb
module ExchangeOfficesHelper
end

app/views/exchange_offices/_form.html.erb
<%= form_for(@exchange_office) do |f| %>
  <% if @exchange_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange_office.errors.count, "error") %> prohibited this exchange_office from being saved:</h2>

      <ul>
      <% @exchange_office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url_page %><br>
    <%= f.text_field :url_page %>
  </div>
  <div class="field">
    <%= f.label :scraping_done %><br>
    <%= f.check_box :scraping_done %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.text_field :message_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchange_offices/edit.html.erb
<h1>Editing Exchange Office</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange_office %> |
<%= link_to 'Back', exchange_offices_path %>

app/views/exchange_offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exchange Offices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url page</th>
      <th>Scrapping done</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchange_offices.each do |exchange_office| %>
      <tr>
        <td><%= exchange_office.name %></td>
        <td><%= exchange_office.url_page %></td>
        <td><%= exchange_office.scraping_done %></td>
        <td><%= exchange_office.message %></td>
        <td><%= link_to 'Show', exchange_office %></td>
        <td><%= link_to 'Edit', edit_exchange_office_path(exchange_office) %></td>
        <td><%= link_to 'Destroy', exchange_office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange office', new_exchange_office_path %>

app/views/exchange_offices/new.html.erb
<h1>New Exchange Office</h1>

<%= render 'form' %>

<%= link_to 'Back', exchange_offices_path %>

app/views/exchange_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exchange_office.name %>
</p>

<p>
  <strong>Url page:</strong>
  <%= @exchange_office.url_page %>
</p>

<p>
  <strong>Scrapping done:</strong>
  <%= @exchange_office.scraping_done %>
</p>

<p>
  <strong>Message:</strong>
  <%= @exchange_office.message %>
</p>

<%= link_to 'Edit', edit_exchange_office_path(@exchange_office) %> |
<%= link_to 'Back', exchange_offices_path %>