config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :scrapings
  resources :form_fields
  resources :prices
  resources :exchange_offices
  resources :messages
  resources :type_form_fields
  resources :price_types
  resources :money

  root 'main#index'

  get '/best_prices', to: 'main#best_prices'
  get '/:exchange_office', to: 'main#price_today_exchange_office'
  get '/date/:exchange_office/:date', to: 'main#price_date_exchange_office'
  get '/all/:exchange_office', to: 'main#all_price_exchange_office'

  post '/main/scraping_done'
  post '/main/scraping_not_done'
  post '/main/destroy_scraping'
  post '/main/replicate_price'

end

app/models/type_form_field.rb
class TypeFormField < ActiveRecord::Base
end

app/controllers/type_form_fields_controller.rb
class TypeFormFieldsController < ApplicationController
  before_action :set_type_form_field, only: [:show, :edit, :update, :destroy]

  # GET /type_form_fields
  # GET /type_form_fields.json
  def index
    @type_form_fields = TypeFormField.all
  end

  # GET /type_form_fields/1
  # GET /type_form_fields/1.json
  def show
  end

  # GET /type_form_fields/new
  def new
    @type_form_field = TypeFormField.new
  end

  # GET /type_form_fields/1/edit
  def edit
  end

  # POST /type_form_fields
  # POST /type_form_fields.json
  def create
    @type_form_field = TypeFormField.new(type_form_field_params)

    respond_to do |format|
      if @type_form_field.save
        format.html { redirect_to @type_form_field, notice: 'Type form field was successfully created.' }
        format.json { render :show, status: :created, location: @type_form_field }
      else
        format.html { render :new }
        format.json { render json: @type_form_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_form_fields/1
  # PATCH/PUT /type_form_fields/1.json
  def update
    respond_to do |format|
      if @type_form_field.update(type_form_field_params)
        format.html { redirect_to @type_form_field, notice: 'Type form field was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_form_field }
      else
        format.html { render :edit }
        format.json { render json: @type_form_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_form_fields/1
  # DELETE /type_form_fields/1.json
  def destroy
    @type_form_field.destroy
    respond_to do |format|
      format.html { redirect_to type_form_fields_url, notice: 'Type form field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_form_field
      @type_form_field = TypeFormField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_form_field_params
      params.require(:type_form_field).permit(:name)
    end
end

app/helpers/type_form_fields_helper.rb
module TypeFormFieldsHelper
end

app/views/type_form_fields/_form.html.erb
<%= form_for(@type_form_field) do |f| %>
  <% if @type_form_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_form_field.errors.count, "error") %> prohibited this type_form_field from being saved:</h2>

      <ul>
      <% @type_form_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/type_form_fields/edit.html.erb
<h1>Editing Type Form Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @type_form_field %> |
<%= link_to 'Back', type_form_fields_path %>

app/views/type_form_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Type Form Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_form_fields.each do |type_form_field| %>
      <tr>
        <td><%= type_form_field.name %></td>
        <td><%= link_to 'Show', type_form_field %></td>
        <td><%= link_to 'Edit', edit_type_form_field_path(type_form_field) %></td>
        <td><%= link_to 'Destroy', type_form_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type form field', new_type_form_field_path %>

app/views/type_form_fields/new.html.erb
<h1>New Type Form Field</h1>

<%= render 'form' %>

<%= link_to 'Back', type_form_fields_path %>

app/views/type_form_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_form_field.name %>
</p>

<%= link_to 'Edit', edit_type_form_field_path(@type_form_field) %> |
<%= link_to 'Back', type_form_fields_path %>