config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :scrapings
  resources :form_fields
  resources :prices
  resources :exchange_offices
  resources :messages
  resources :type_form_fields
  resources :price_types
  resources :money

  root 'main#index'

  get '/best_prices', to: 'main#best_prices'
  get '/:exchange_office', to: 'main#price_today_exchange_office'
  get '/date/:exchange_office/:date', to: 'main#price_date_exchange_office'
  get '/all/:exchange_office', to: 'main#all_price_exchange_office'

  post '/main/scraping_done'
  post '/main/scraping_not_done'
  post '/main/destroy_scraping'
  post '/main/replicate_price'

end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :money
  belongs_to :exchange_office
  belongs_to :price_type

  def self.find_min_max_price

  	prices = Price.select("max(price) as price, date, price_types.name as name_price_type, exchange_offices.name as name_exchange_office, money.name as name_money")
                     .joins(:price_type)
                     .joins(:exchange_office)
                     .joins(:money)
                     .where("date = ? and price_types.name = ?", Date.today, "Compra")
                     .group("money_id")

    prices += Price.select("min(price) as price, date, price_types.name as name_price_type, exchange_offices.name as name_exchange_office, money.name as name_money")
                     .joins(:price_type)
                     .joins(:exchange_office)
                     .joins(:money)
                     .where("date = ? and price_types.name = ?", Date.today, "Venta")
                     .group("money_id")

    @prices = Price.select("price, date, price_types.name as name_price_type, exchange_offices.name as name_exchange_office, money.name as name_money")
                     .joins(:price_type)
                     .joins(:exchange_office)
                     .joins(:money)
                     .where("date = ?", Date.today)
                     .order("exchange_office_id")
                     .order("price_type_id")

  end

  def self.find_by_exchange_office_and_date exchange_office, date

  	Price.select("price, date, price_types.name as name_price_type, exchange_offices.name as name_exchange_office, money.name as name_money")
  		.joins(:price_type)
  		.joins(:exchange_office)
  		.joins(:money)
  		.where("exchange_offices.name = ? and date = ?", exchange_office_format(exchange_office), date)

  end

  def self.find_by_exchange_office exchange_office

  	Price.select("price, date, price_types.name as name_price_type, exchange_offices.name as name_exchange_office, money.name as name_money")
  		.joins(:price_type)
  		.joins(:exchange_office)
  		.joins(:money)
  		.where("exchange_offices.name = ?", exchange_office_format(exchange_office))

  end

  def self.update_or_create data, money_price, date

    price = Price.find_or_initialize_by(date: date, money_id: data.money.id, exchange_office_id: data.exchange_office.id, price_type_id: data.price_type.id)
    price.price = price_scraping_format(money_price)
    price.save

  end

  def self.replicate_price

    Price.where(date: Date.today).each do |price|
      update_or_create(price, price.price.to_s, (Date.today + 1))
    end

  end

  def self.price_scraping_format money_price

  	return (money_price.gsub(',', '.').match(/\d+(\.\d+)?/)).to_s.to_f

  end

  def self.exchange_office_format(nombre)

    return nombre.split(/(?=[A-Z])/).join(' ').titleize

  end
end

app/models/price_type.rb
class PriceType < ActiveRecord::Base
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit

    if @price.date != Date.today
      # Redireccionar a acceso denegado
      redirect_to root_path
    end

  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:price, :date, :money_id, :exchange_office_id, :price_type_id)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :money_id %><br>
    <%= f.text_field :money_id %>
  </div>
  <div class="field">
    <%= f.label :exchange_office_id %><br>
    <%= f.text_field :exchange_office_id %>
  </div>
  <div class="field">
    <%= f.label :price_type_id %><br>
    <%= f.text_field :price_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prices</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Date</th>
      <th>Money</th>
      <th>Exchange office</th>
      <th>Price type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.price %></td>
        <td><%= price.date %></td>
        <td><%= price.money.name %></td>
        <td><%= price.exchange_office.name %></td>
        <td><%= price.price_type.name %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @price.date %>
</p>

<p>
  <strong>Money:</strong>
  <%= @price.money %>
</p>

<p>
  <strong>Exchange office:</strong>
  <%= @price.exchange_office %>
</p>

<p>
  <strong>Price type:</strong>
  <%= @price.price_type %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>