config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :scrapings
  resources :form_fields
  resources :prices
  resources :exchange_offices
  resources :messages
  resources :type_form_fields
  resources :price_types
  resources :money

  root 'main#index'

  get '/best_prices', to: 'main#best_prices'
  get '/:exchange_office', to: 'main#price_today_exchange_office'
  get '/date/:exchange_office/:date', to: 'main#price_date_exchange_office'
  get '/all/:exchange_office', to: 'main#all_price_exchange_office'

  post '/main/scraping_done'
  post '/main/scraping_not_done'
  post '/main/destroy_scraping'
  post '/main/replicate_price'

end

app/controllers/price_types_controller.rb
class PriceTypesController < ApplicationController
  before_action :set_price_type, only: [:show, :edit, :update, :destroy]

  # GET /price_types
  # GET /price_types.json
  def index
    @price_types = PriceType.all
  end

  # GET /price_types/1
  # GET /price_types/1.json
  def show
  end

  # GET /price_types/new
  def new
    @price_type = PriceType.new
  end

  # GET /price_types/1/edit
  def edit
  end

  # POST /price_types
  # POST /price_types.json
  def create
    @price_type = PriceType.new(price_type_params)

    respond_to do |format|
      if @price_type.save
        format.html { redirect_to @price_type, notice: 'Price type was successfully created.' }
        format.json { render :show, status: :created, location: @price_type }
      else
        format.html { render :new }
        format.json { render json: @price_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_types/1
  # PATCH/PUT /price_types/1.json
  def update
    respond_to do |format|
      if @price_type.update(price_type_params)
        format.html { redirect_to @price_type, notice: 'Price type was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_type }
      else
        format.html { render :edit }
        format.json { render json: @price_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_types/1
  # DELETE /price_types/1.json
  def destroy
    @price_type.destroy
    respond_to do |format|
      format.html { redirect_to price_types_url, notice: 'Price type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_type
      @price_type = PriceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_type_params
      params.require(:price_type).permit(:name)
    end
end

app/helpers/price_types_helper.rb
module PriceTypesHelper
end

app/views/price_types/_form.html.erb
<%= form_for(@price_type) do |f| %>
  <% if @price_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price_type.errors.count, "error") %> prohibited this price_type from being saved:</h2>

      <ul>
      <% @price_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_types/edit.html.erb
<h1>Editing Price Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @price_type %> |
<%= link_to 'Back', price_types_path %>

app/views/price_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Price Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_types.each do |price_type| %>
      <tr>
        <td><%= price_type.name %></td>
        <td><%= link_to 'Show', price_type %></td>
        <td><%= link_to 'Edit', edit_price_type_path(price_type) %></td>
        <td><%= link_to 'Destroy', price_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price type', new_price_type_path %>

app/views/price_types/new.html.erb
<h1>New Price Type</h1>

<%= render 'form' %>

<%= link_to 'Back', price_types_path %>

app/views/price_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price_type.name %>
</p>

<%= link_to 'Edit', edit_price_type_path(@price_type) %> |
<%= link_to 'Back', price_types_path %>